esphome:
  name: seeedstudio-mr60bha2-kit-8e65b4

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

# --- UART: mmWave radar talks over UART ---
uart:
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

# --- Enable the MR60BHA2 radar component ---
seeed_mr60bha2:
  uart_id: uart_bus

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 1s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
    num_targets:
      name: "Target Number"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESPHome-${name}"
    password: "esphome123"

captive_portal:

logger:
  level: DEBUG

api:
ota:
  platform: esphome

web_server:
  port: 80