esphome:
  name: seeedstudio-mr60bha2-kit-8e65b4

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# --- UART: mmWave radar talks over UART ---
uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
# --- Enable the MR60BHA2 radar component ---
seeed_mr60bha2:

# --- Person / presence detection ---
binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Detected"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:
  platform: esphome

